name: mate_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.0
  provider: ^4.3.2
  intl: ^0.17.0
  http: ^0.13.1
  flutter_beautiful_popup: ^1.4.0
  #  qrscan: ^0.2.17
  carousel_slider: ^2.2.1
  shared_preferences: ^2.0.15
  json_annotation: ^4.5.0
  #flutter_advanced_networkimage: ^0.2.2
  fluttertoast: ^7.1.1
  google_sign_in: ^5.0.1    #4.5.6
  firebase_messaging: ^13.1.0
  firebase_crashlytics: ^2.9.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.3.10
  firebase_core: ^1.24.0
  firebase_database: ^6.0.0
  firebase_storage: ^10.3.11
  firebase_dynamic_links: ^4.3.11
  shimmer: ^1.1.2
  nuts_activity_indicator: ^0.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  permission_handler: ^10.1.0
  flutter_native_image: ^0.0.6+1
  cached_network_image: ^3.2.0
  photo_view: ^0.10.2
  flutter_spinkit: ^4.1.2+1
  video_player: ^2.2.16
  dio: ^4.0.6
  flutter_svg: ^0.22.0
  video_compress: ^3.1.0
  #  flutter_statusbarcolor: ^0.2.3
  googleapis: ^1.0.0
  googleapis_auth: ^1.0.0
  url_launcher: ^6.0.5
  dotted_border: ^2.0.0
  expandable_text: ^2.2.0
  share: ^2.0.4
  flutter_linkify: ^5.0.2
  flutter_reaction_button: ^2.0.0+1
  flutter_switch: ^0.3.2
  #  datetime_picker_formfield: ^1.0.0
  flutter_share_me: ^1.2.0
  #  datetime_picker_formfield: ^1.0.0
  overlay_support: ^1.2.1
  file_picker: ^4.5.0
  #open_file: ^3.2.1
  webview_flutter: ^2.0.14
  #  flutter_webview_plugin: ^0.4.0
  flutter_inappwebview: ^5.3.2
  store_redirect: ^2.0.1
  package_info_plus: ^1.4.0
  sizer: ^1.1.8
  flutter_speed_dial: ^5.0.0+1
  giphy_picker: ^2.0.0
  google_fonts: ^3.0.1
  intro_slider: ^2.3.1
  liquid_progress_indicator: ^0.4.0
#  flutter_contacts: ^1.1.3
  agora_rtc_engine: ^5.3.1    #1.0.15
  focused_menu: ^1.0.2
  smooth_page_indicator: ^0.2.3
  dropdown_search: ^3.0.1
  flutter_local_notifications: ^12.0.3
  #swipe_to: ^1.0.2
  record: ^4.4.3
  just_audio: ^0.9.30
  vibration: ^1.7.6
  #callkeep: ^0.3.3
  animated_text_kit: ^4.2.1
  #ffmpeg_kit_flutter: ^5.1.0
  card_swiper: ^2.0.4
  stacked_firebase_auth: ^0.2.1
  flutter_slidable: ^2.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

# flutter pub run flutter_launcher_icons:main -f assets/logo1.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/asset/Reactions/
    - lib/asset/ChatReactionImage/
    - lib/asset/logo.png
    - lib/asset/demo.png
    - lib/asset/glogo.png
    - lib/asset/molla.png
    - lib/asset/molla2.png
    - assets/logo1.png
    - lib/asset/
    - lib/asset/Social_Icons/
    - lib/asset/icons/
    - lib/asset/icons/home.png
    - lib/asset/icons/home-active.png
    - lib/asset/icons/school.png
    - lib/asset/icons/school-active.png
    - lib/asset/icons/search.png
    - lib/asset/icons/search-active.png
    - lib/asset/icons/study-group.png
    - lib/asset/icons/study-group-active.png
    - lib/asset/icons/profile-cover.png
    - lib/asset/icons/home-icon.svg
    - lib/asset/chatPageAssets/
    - lib/asset/homePageIcons/
    - lib/asset/introAssets/
    - lib/asset/iconsNewDesign/
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Opensans
      fonts:
        - asset: lib/asset/fonts/OpenSans-Regular.ttf
        - asset: lib/asset/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: lib/asset/fonts/Quicksand-Regular.ttf
        - asset: lib/asset/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: lib/asset/fonts/Poppins-Regular.ttf
        - asset: lib/asset/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/asset/fonts/Poppins-SemiBold.ttf
          weight: 500

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
